# Usa uma imagem leve do Node.js (versão 18 ou 20)
FROM node:20-alpine

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências primeiro (para aproveitar o cache do Docker)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código do projeto para dentro do container
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# Comando para rodar o projeto em modo desenvolvimento
# O "--host" é OBRIGATÓRIO para o Docker conseguir acessar o navegador
CMD ["npm", "run", "dev", "--", "--host"]